#!/usr/bin/env python3

import psutil
import neovim

str = open('/home/bresilla/.cache/wal/theme', 'r').read().replace('\n', '')
addresses = []

for proc in psutil.process_iter(attrs=['name']):
    if proc.info['name'] == 'nvim':
        try:
            # for conn in proc.connections('inet4'):
            #     addresses.insert(0, ':'.join(map(str, conn.laddr)))
            # for conn in proc.connections('inet6'):
            #     addresses.insert(0, ':'.join(map(str, conn.laddr)))
            for conn in proc.connections('unix'):
                if conn.laddr:
                    addresses.insert(0, conn.laddr)
        except psutil.AccessDenied:
            continue

for addr in sorted(addresses):
    nvim = neovim.attach('socket', path=addr)
    try:
        nvim.command(':lua mycolors("' + str +'")')
    finally:
        continue

# IN BASH USING NEOVIM-REMOTE
# while read SERVER
# do
#     # echo ${SERVER}
#     if [[ ${SERVER:0:1} == "/" ]]; then
#         /home/bresilla/.local/bin/nvr --nostart --servername $SERVER -c ":lua mycolors(\"$(cat /home/bresilla/.cache/wal/theme)\")" &
#     fi
# done <<< $( echo -e "$(/home/bresilla/.local/bin/nvr --serverlist)" )
